language: python
python:
  - 3.7
addons:
  postgresql: "9.5"
services: postgresql
before_install:
  - export DJANGO_SETTINGS_MODULE=alyx.settings
  - export PYTHONPATH=$HOME/builds/cortexlab/alyx
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
script:
  - cd alyx
  - python manage.py test -n
  - flake8 .
