services:
  postgres:
    image: postgres:17
    container_name: alyx_postgres
    env_file: ../alyx/alyx/.env_prod
    volumes:
      - alyx_postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    command: -p ${POSTGRES_PORT:-5432}
volumes:
  alyx_postgres:
